# Define the appenders
appenders = console

appender.console.type = Console
appender.console.name = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Define the root logger and set its level to DEBUG
#rootLogger.level = error
#rootLogger.appenderRef.console.ref = CONSOLE

logger.task.name = org.example.TaskKMeans
logger.task.level = info
#logger.task.appenderRef.console.ref = CONSOLE